### ISSUE TITLE
Just to thank you for this package.

### ISSUE THREAD

**Issue by fntneves** [juampi92/cursor-pagination#12]
Hello,

This is not actually an issue. 
This is just a message to thank you for this package. This is exactly what I was looking for.

Thank you.

**Comment by juampi92** [comment]
Thanks a lot man!
Any PR with new ideas, documentation improvements, etc are welcome! Glad you found it useful :)

**Comment by juampi92** [comment]
Hey man!

Thanks for saying that, I'm glad you found it useful 🙂

Any PR with new ideas, documentation improvements, etc are welcome!
