### ISSUE TITLE
Descending order queries

### ISSUE THREAD

**Issue by joelennon** [juampi92/cursor-pagination#13]
Hi,

Great work, awesome package!

One thing I'm having some trouble with is using this package on a dataset where I'm using a descending order by.  If I order by ascending on ID or created_at, it works great - but when I try to order by descending ID or created_at, I get the following results:

* `orderBy('id', 'DESC')` - no results
* `orderBy('created_at', 'DESC')` - loads the first page no problem, 2nd page has no results

My use case for this is to show an infinite scrolling feed of posts - with newest posts showing first, hence needing to order by descending ID.

Am I missing something or doing something wrong?

Thanks in advance,
Joe

**Comment by juampi92** [comment]
Hey Joe, can you send me the whole Query builder definition?

**Comment by joelennon** [comment]
Thanks for responding! This is from my controller action.

```
Post::with('user')->orderBy('id', 'desc')->cursorPaginate();
```

**Comment by juampi92** [comment]
Can you run `DB::enableQueryLog()`; before, and `dd(DB::getQueryLog());` afterwards?

It should output something like
```mysql
select * from `post` where `post`.`deleted_at` is null order by `id` desc limit 16
```

and
```mysql
select * from `user` where `user`.`id` in (?, ?, ...);
```

**Comment by joelennon** [comment]
Aha, turns out I was incorrectly passing `?next_cursor=null` when fetching the first page which caused the query to return zero results. Omitting the query string on the first page resolved the issue.

Thanks again for the great package!
