### ISSUE TITLE
total count of results is not showing up 

### ISSUE THREAD

**Issue by aliwesome** [juampi92/cursor-pagination#16]
I cannot find any value with name `total` in meta array in response.

**Comment by wajdijurry** [comment]
+1

**Comment by AlexNovicov** [comment]
+1

**Comment by juampi92** [comment]
The reason is because it's not a length aware paginator.

**Comment by wajdijurry** [comment]
@juampi92 I guess it's too early to explain. You should take 2 years to respond.

Have a nice day!
