### ISSUE TITLE
No way to use camelCase query parameters names

### ISSUE THREAD

**Issue by antonkomarev** [juampi92/cursor-pagination#3]
I was wanted to has query parameter `?nextCursor={cursor}`, but there is no way to do that. You force underscore in names and this is not configurable.

https://github.com/juampi92/cursor-pagination/blob/5d27c6c39734d37dd89cf744e821a5215f9c8e3f/src/CursorPaginator.php#L112-L115

Some APIs has `kebab-case` parameters too. So it would be great to have configurable parameter words separator. Or just let developer to define fully qualified parameters, and not parts of them in config.

**Comment by juampi92** [comment]
Noted.

**Comment by juampi92** [comment]
Deployed on v1.1.0.

Use config `'transform_name' => 'camel_case'`
or `'transform_name' => 'kebab_case'`, or your function name. 

It'll be called with `call_user_func` on the name.

Check default config file.

**Comment by juampi92** [comment]
mmm I may replace this to a more customizable output
