### ISSUE TITLE
No render method?

### ISSUE THREAD

**Issue by garygreen** [juampi92/cursor-pagination#4]
Is there a reason why there isn't a method to render the pagination links? I would of thought it could still render using the "simple" pagination view?

**Comment by juampi92** [comment]
Is not that simple though.

The Readme states that this type of pagination is not good for retrieving previous items like a paged pagination. It does not fetch the n-1 items when you go to the previous page, It's perfect for moving forward (next), but when you try to go backwards, you'll have to rely on the FrontEnd storing the previous items.

Let me know if this answer is not clear.

**Comment by garygreen** [comment]
> you'll have to rely on the FrontEnd storing the previous items.

Isn't that what the previous cursor is for?

**Comment by juampi92** [comment]
No. It gives you records created before that cursor, but not the n-1.

It's explained on the [readme](https://github.com/juampi92/cursor-pagination#understanding-the-previous-cursor). If you have from 1 to 10 ids. The current cursor is 8 and the perPage is 2, if you do previous=8, it wont return 6 and 7 like simple pagination does. It'll return 1, 2.

This pagination works just like instagram's / github's, etc.

**Comment by garygreen** [comment]
Right, gotcha. I think the confusion really is because the naming of the methods doesn't translate very well to cursor based pagination, in particular the `previousPageUrl()` method. The word "previous" in this package relates to the CURRENT "page"/range being viewed and it's the min id of that. It's not "previous" at all in the traditional pagination sense.

Currently, it doesn't support knowing what the previous url should be, as you mention to do this would require storing the previous cursor position on the LAST page/range displayed in order to link back to it.

Imo the `previousPageUrl` is particularly misleading atm and really it should be discouraged to be used as it's meaning is completely different to the intended use of pagination - linking to the previous page, not start of the current cursor range.

It would be good if previous page url could be supported in this package, otherwise you can only move forwards in the pagination and not back. It would technically be possible if you stored the previous page cursor in the url.

**Comment by juampi92** [comment]
> The word "previous" in this package relates to the CURRENT "page"/range being viewed and it's the min id of that. It's not "previous" at all in the traditional pagination sense.

EXACTLY.

The thing is, I extended it from AbstractPaginator, so I had to redefine those methods. 

>  It would technically be possible if you stored the previous page cursor in the url.

Yes. What the previous and next cursors do is take the first or last identifier (might be 'id' or 'created_at', for example), and search from there or up to there. So the 'previous' functionality is just for fetching NEW items and don't get duplicated results (like you would if you fetch the full page 0 when there's only one new item).

I think I should make it clearer on the Readme. It's a lot of text, maybe a gif will make it easier to get.

**Comment by garygreen** [comment]
Yeah it's the word "previous" that is super confusing. Personally, I prefer the terminology "min" or "start" as previous implies that it's the previous result set, and previous in pagination always means the last page and by no means refers to the "current" result set / page.

A gif might help, though I have quite a small brain so maybe other people won't struggle to get their head round it as much as me 😆

**Comment by juampi92** [comment]
Those are configurable! But only the exposed URL parameters, not the paginator's methods.

**Comment by garygreen** [comment]
I'm wondering if maybe the `identifier_sort_inverted` in the service provider could be used to somehow provide back/previous page functionality. If I invert that, it starts going back essentially...

**Comment by garygreen** [comment]
So the previous url would just be the next_cursor and invert the current sort direction...

**Comment by juampi92** [comment]
It can be done, don't get me wrong. But it's out of scope for the purpose of this type of cursor-pagination. I followed API standards, not trying to make page pagination using cursors.

If you invert the sort identifier, query the items, and then invert the order of the items, you'll get the n-1 results.

**Comment by garygreen** [comment]
> But it's out of scope for the purpose of this type of cursor-pagination. I followed API standards, not trying to make page pagination using cursors.

The problem is it's been hacked into the Laravel pagination, which means it currently feels like a half complete thing if it doesn't support going back a page, IMO. Might be worth noting that in the documentation that if you wish to support going back you need extra stuff to get it to work. Lots of infinite scrollers out there have a "previous" button to go back to the previous set of results, it's not unusual.

> If you invert the sort identifier, query the items, and then invert the order of the items, you'll get the n-1 results.

Will give it a try, cheers

**Comment by garygreen** [comment]
You mention the pagination works exactly like github, but they have the ability to link to the previous page?

![image](https://user-images.githubusercontent.com/1702638/38389931-bd5ce6a6-3917-11e8-970b-fb6820ea99f8.png)

That's why I'm a bit confused with the whole "previous_cursor" usage.

**Comment by juampi92** [comment]
I meant the github GraphSQL API, but you are right, it should support it, somehow, and it should have those links organized better. Maybe rename the `previous` to `min` and but also include previous functionality, although it implicates a huge refactor.

**Comment by garygreen** [comment]
It looks like github uses the same technique that OkCupid use and probably lots of other sites as well, they define a +<number of items> with a before/after reference id

So, pivot point `d60b1c1a40c2e8f42e69625dfe75d4046f8247e8`

Page 2 = https://github.com/laravel/framework/commits/5.6?after=d60b1c1a40c2e8f42e69625dfe75d4046f8247e8+34

Linking back to page 1:

https://github.com/laravel/framework/commits/5.6?before=d60b1c1a40c2e8f42e69625dfe75d4046f8247e8+35

Page 5: https://github.com/laravel/framework/commits/5.6?after=d60b1c1a40c2e8f42e69625dfe75d4046f8247e8+139

There are 35 items to a page

**Comment by juampi92** [comment]
Mmm that sounds like a page pagination, but using a cursor so the pages don't get duplicated values when a new item is added.
That's not the idea of this package still, but I like how you are facing this.

**Comment by garygreen** [comment]
> That's not the idea of this package

I'll hack on my own fork of this then 😄
