### ISSUE TITLE
Question: is it possible to get previous page/Items?

### ISSUE THREAD

**Issue by amrnn90** [juampi92/cursor-pagination#6]
Hello, I want to know if it's possible to retrieve previous page/items? 
I read this in the cons section:

> No previous page, although the browser still has them.

But then I read about the previous cursor, so I'm a little bit confused about what's possible and what's not. 
Thanks.

**Comment by juampi92** [comment]
Yes, Sorry. The readme is kind of unclear. You could read this discussion, maybe you'll get my motive here:
https://github.com/juampi92/cursor-pagination/issues/4

If you are still lost, let me know. But yes, I need to make a gif or something explaining the flow.
